### ISSUE TITLE
Readme.md typos: 

### ISSUE THREAD

**Issue by lgbaeza** [digexp/MACM-SDK-android#1]
**Querying a list of content items by path**
_request.addProperties(CAASProperties.OIS, CAASProperties.CONTENT_TYPE, CAASProperties.TITLE..._ should be
_request.addProperties(CAASProperties.**OID**, CAASProperties.CONTENT_TYPE, CAASProperties.TITLE..._ 
**Querying an asset (image) by its url**
_Bitmap bitmap = BitmapFactory.decodeByteArray(bytes, 0, bytes.length)_ should be _BitmapFactory.decodeByteArray(**requestResult.getResult()**, 0, **requestResult.getResult().length**)_

**Comment by argaha** [comment]
the readme has been updated
